#!/usr/bin/env node

/**
 * Image Optimization
 *
 * Two things, both deliberately conservative:
 *
 * 1. Compress JPEG/PNG images IN PLACE (same filename, same path) using
 *    sharp. This needs zero HTML changes and can't break anything — every
 *    existing <img src>, CSS background-image, and srcset reference keeps
 *    working exactly as before, just pointing at a smaller file.
 *
 * 2. Generate a .webp SIBLING next to each compressed image (same
 *    directory, same basename, .webp extension) for future opt-in use.
 *    We do NOT rewrite HTML to <picture>/srcset here — this is a legacy
 *    WordPress + Elementor + WooCommerce export with background-images set
 *    via inline styles and CSS classes in ~77 pages, plus lazy-load
 *    libraries that expect specific markup. Regex-rewriting all of that
 *    reliably is a separate, higher-risk piece of work; the .webp files
 *    are ready whenever that's done properly (see README "What's not done
 *    yet").
 *
 * Only overwrites a file if the optimized version is actually smaller —
 * never makes an image bigger or lower quality for no reason.
 *
 * Run standalone: node scripts/optimize.js
 * (Not wired into `npm run build` — it's slow-ish and shouldn't re-run on
 * every build since dist/ images are already committed as optimized.)
 */

const fs = require('fs');
const path = require('path');

let sharp;
try {
  sharp = require('sharp');
} catch (e) {
  console.error('\n❌ sharp is not installed. Run: npm install --save-dev sharp\n');
  process.exit(1);
}

const DIST = path.join(__dirname, '../dist');
const JPEG_QUALITY = 80;
const PNG_QUALITY = 80;
const WEBP_QUALITY = 80;

function findImages(dir, results = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      findImages(full, results);
    } else if (/\.(jpe?g|png)$/i.test(entry.name)) {
      results.push(full);
    }
  }
  return results;
}

/**
 * Ownership + provenance tags re-applied on every re-encode.
 *
 * sharp drops all metadata unless told otherwise, so this step was silently
 * undoing the branding written by scripts/generate-ai-images.js: the source
 * files in assets/ carried the tags, the copies actually served from dist/
 * carried none. Verified against the deployed URL, not just on disk — that
 * is where the discrepancy showed up.
 *
 * WHY THIS IS THREE CASES AND NOT ONE
 *
 * The first version stamped one metadata block onto every image dist/
 * contains. Measured afterwards: 252 files carried it, and 92 of those are
 * not Virtual Marketer images at all — bundled js_composer and LayerSlider
 * plugin icons, theme graphics, and photographs uploaded to the old
 * WordPress site. Each of those 92 asserted two things that are false:
 *
 *   - "© SGS Virtual Marketer GmbH" on artwork owned by a plugin vendor.
 *   - "AI-generated image produced with Virtual Marketer" on a photograph
 *     and on hand-drawn icons.
 *
 * The second one is the serious half. The AI-origin tag is the machine-
 * readable marking the site's own privacy policy points to for Art. 50(2)
 * of the AI Act. A marking that is applied to everything indiscriminately
 * carries no information: if a photograph and a generated image are tagged
 * identically, the tag no longer distinguishes synthetic content, which is
 * the entire point of the obligation. Over-marking devalues the marking in
 * the same way stripping it would.
 *
 * So provenance now follows what the file actually is:
 *
 *   ai         assets/product-pages/ — output of generate-ai-images.js.
 *              Ownership + the AI-origin marking.
 *   own        Other Virtual Marketer material (own assets, uploads from
 *              the old site). Ownership only. No AI claim: these are
 *              photographs and logos, and saying otherwise is a false
 *              provenance statement.
 *   thirdparty Theme and plugin payloads. Metadata left exactly as shipped —
 *              claiming authorship of someone else's icon set is a
 *              copyright assertion this company cannot make.
 *
 * If a new directory of generated images is added, add it to AI_TREES.
 * Defaulting an unknown path to `own` is the safe direction: it under-claims
 * rather than inventing an AI origin.
 */
const OWNER = 'SGS Virtual Marketer GmbH';
const AI_MARK = 'AI-generated image produced with Virtual Marketer';

/**
 * Paths (relative to dist/) whose contents are AI-generated by this repo.
 * Note the path: generate-ai-images.js writes to assets/product-pages/ in the
 * source tree, but the build copies it to the site root as /product-pages/,
 * and this script reads dist/. Matching the source path here silently
 * classified all 160 generated images as `own` and dropped their AI marking.
 */
const AI_TREES = ['product-pages'];
/** Paths whose contents ship with a theme or plugin and are not ours. */
const THIRD_PARTY_TREES = ['wp-content/themes', 'wp-content/plugins', 'wp-includes'];

function classify(file) {
  const rel = path.relative(DIST, file).split(path.sep).join('/');
  if (AI_TREES.some((t) => rel.startsWith(t + '/'))) return 'ai';
  if (THIRD_PARTY_TREES.some((t) => rel.startsWith(t + '/'))) return 'thirdparty';
  return 'own';
}

/** ImageDescription for non-AI material. Must be set, never omitted — see below. */
const OWN_MARK = 'Virtual Marketer — virtual-marketer.de';

function metadataFor(kind) {
  if (kind === 'thirdparty') return null;
  return {
    exif: {
      IFD0: {
        Artist: OWNER,
        Copyright: `© ${OWNER} — virtual-marketer.de`,
        Software: 'Virtual Marketer',
        // ImageDescription is written for BOTH classes, with different text,
        // and must not simply be left out for `own`. sharp's withMetadata()
        // MERGES into the input file's existing EXIF instead of replacing it,
        // so omitting a tag leaves whatever was there before. An earlier
        // build had stamped the AI marking onto every image; omitting the tag
        // here left 42 photographs and logos still claiming to be AI-
        // generated. Overwriting it is what actually clears the false claim.
        ImageDescription: kind === 'ai' ? AI_MARK : OWN_MARK,
      },
    },
  };
}

/**
 * True if `file` already carries exactly the provenance its class calls for.
 *
 * For third-party files "correct" means our tags are ABSENT — an earlier run
 * stamped them onto plugin icons, and re-encoding without withMetadata() is
 * what removes them again. Returning true unconditionally here would leave
 * that false copyright and false AI marking in place forever.
 */
async function hasCorrectMetadata(file, kind) {
  let exif = '';
  try {
    const meta = await sharp(file).metadata();
    exif = meta.exif ? meta.exif.toString('latin1') : '';
  } catch {
    return false;
  }
  if (kind === 'thirdparty') return !exif.includes(OWNER) && !exif.includes(AI_MARK);
  if (!exif.includes(OWNER)) return false;
  // An AI mark on a non-AI file is as wrong as a missing one on an AI file.
  return exif.includes(AI_MARK) === (kind === 'ai');
}

async function optimizeOne(file) {
  const originalSize = fs.statSync(file).size;
  const ext = path.extname(file).toLowerCase();
  const isJpeg = ext === '.jpg' || ext === '.jpeg';
  const kind = classify(file);
  const meta = metadataFor(kind);

  try {
    // sharp keeps no metadata by default; for third-party files that is the
    // wanted behaviour, so they are copied through untouched instead.
    const withMeta = (pipeline) => (meta ? pipeline.withMetadata(meta) : pipeline);

    // 1. In-place lossy recompression (same format, same path)
    const optimizedBuffer = isJpeg
      ? await withMeta(sharp(file)).jpeg({ quality: JPEG_QUALITY, mozjpeg: true }).toBuffer()
      : await withMeta(sharp(file)).png({ quality: PNG_QUALITY, compressionLevel: 9, palette: true }).toBuffer();

    // Writing only when the result is smaller used to mean an already-well-
    // compressed file kept whatever provenance it had — which is how images
    // ended up served without the marking their source carried. Wrong or
    // absent provenance is now reason enough to write on its own.
    const metadataWrong = !(await hasCorrectMetadata(file, kind));
    let newSize = originalSize;
    if (optimizedBuffer.length < originalSize || metadataWrong) {
      fs.writeFileSync(file, optimizedBuffer);
      newSize = optimizedBuffer.length;
    }

    // 2. WebP sibling (additive — never overwrites source, only skipped if
    //    it already exists, is up to date with the source's mtime, and
    //    already carries the right provenance)
    const webpPath = file.replace(/\.(jpe?g|png)$/i, '.webp');
    const webpExists = fs.existsSync(webpPath);
    const sourceStillFresh =
      webpExists &&
      fs.statSync(webpPath).mtimeMs >= fs.statSync(file).mtimeMs &&
      (await hasCorrectMetadata(webpPath, kind));

    let webpSize = null;
    if (!sourceStillFresh) {
      const webpBuffer = await withMeta(sharp(file)).webp({ quality: WEBP_QUALITY }).toBuffer();
      fs.writeFileSync(webpPath, webpBuffer);
      webpSize = webpBuffer.length;
    } else {
      webpSize = fs.statSync(webpPath).size;
    }

    return { file, kind, originalSize, newSize, webpSize, skipped: false };
  } catch (err) {
    return { file, originalSize, error: err.message, skipped: true };
  }
}

async function main() {
  console.log('\n📦 Image Optimization\n');

  const images = findImages(DIST);
  console.log(`Found ${images.length} JPEG/PNG images in dist/\n`);

  let totalBefore = 0;
  let totalAfter = 0;
  let totalWebp = 0;
  let errors = 0;

  for (const file of images) {
    const result = await optimizeOne(file);
    const rel = path.relative(DIST, result.file);

    if (result.skipped) {
      console.log(`  ⚠ ${rel} — ${result.error}`);
      errors++;
      continue;
    }

    totalBefore += result.originalSize;
    totalAfter += result.newSize;
    totalWebp += result.webpSize;

    const savedPct = result.originalSize > 0
      ? Math.round((1 - result.newSize / result.originalSize) * 100)
      : 0;

    if (savedPct > 0) {
      console.log(`  ✓ ${rel} — ${(result.originalSize / 1024).toFixed(0)}KB → ${(result.newSize / 1024).toFixed(0)}KB (-${savedPct}%), webp: ${(result.webpSize / 1024).toFixed(0)}KB`);
    } else {
      console.log(`  · ${rel} — already optimal, webp: ${(result.webpSize / 1024).toFixed(0)}KB`);
    }
  }

  console.log('\n' + '='.repeat(60));
  console.log('✅ Image Optimization Complete\n');
  console.log(`  Images processed:     ${images.length - errors}`);
  if (errors) console.log(`  Errors:                ${errors}`);
  console.log(`  Original size:        ${(totalBefore / 1024 / 1024).toFixed(2)} MB`);
  console.log(`  Optimized size:       ${(totalAfter / 1024 / 1024).toFixed(2)} MB`);
  console.log(`  Saved:                ${((totalBefore - totalAfter) / 1024 / 1024).toFixed(2)} MB (${totalBefore > 0 ? Math.round((1 - totalAfter / totalBefore) * 100) : 0}%)`);
  console.log(`  WebP siblings total:  ${(totalWebp / 1024 / 1024).toFixed(2)} MB (available for future <picture> adoption)\n`);

  await verifyProvenance();
}

/**
 * Re-reads every image from disk and checks the provenance actually written.
 *
 * This is not belt-and-braces. The bug this file was fixed for was invisible
 * in the code: the metadata was passed to sharp correctly and still did not
 * reach the served file, because the write was conditional on the result
 * being smaller. Only reading the bytes back catches that class of failure,
 * so the build now says out loud what each image claims about itself.
 *
 * WebP siblings are included — they are what browsers actually fetch.
 */
async function verifyProvenance() {
  const all = [];
  (function walk(dir) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (/\.(jpe?g|png|webp)$/i.test(entry.name)) all.push(full);
    }
  })(DIST);

  const counts = { ai: 0, own: 0, thirdparty: 0 };
  const wrong = [];
  for (const file of all) {
    const kind = classify(file);
    counts[kind]++;
    if (!(await hasCorrectMetadata(file, kind))) wrong.push(`${kind}: ${path.relative(DIST, file)}`);
  }

  console.log('🔎 Image provenance');
  console.log(`  AI-generated (marked "${AI_MARK}"): ${counts.ai}`);
  console.log(`  Own material (ownership only, no AI claim): ${counts.own}`);
  console.log(`  Third-party theme/plugin assets (untouched): ${counts.thirdparty}`);

  if (wrong.length) {
    console.log(`\n  ⚠ ${wrong.length} image(s) carry the wrong provenance:`);
    wrong.slice(0, 15).forEach((w) => console.log(`      ${w}`));
    if (wrong.length > 15) console.log(`      … and ${wrong.length - 15} more`);
    process.exitCode = 1;
  } else {
    console.log('  ✓ every image states its origin correctly\n');
  }
}

main();
