#!/usr/bin/env node

/**
 * Points CSS background-images and <img> tags at the WebP files that
 * optimize.js already generates.
 *
 * The .webp siblings have existed for a while and nothing referenced them —
 * the build produced 5.6 MB of WebP that no browser ever requested. On the
 * homepage that meant three PNG backgrounds worth 656 KB were being
 * downloaded when the same images as WebP come to 217 KB:
 *
 *     Background-Virtual-Marketer-2.png   265 KB → 105 KB
 *     Background-Virtual-Marketer-1.png   219 KB →  27 KB
 *     Virtual-Marketer-Banner-.png        172 KB →  85 KB
 *
 * That is the largest single payload on the page and the reason LCP sat at
 * 7.7 s after the dead scripts were removed.
 *
 * WHY REWRITE IN PLACE RATHER THAN EMIT <picture>
 *
 * <picture> with a fallback <source> is the textbook answer and the wrong one
 * here. Most of these references are CSS background-images, which <picture>
 * cannot express at all, and the rest are inside a WordPress + Elementor
 * export whose markup is regenerated by other build steps. A flat rewrite
 * works identically for both cases.
 *
 * The cost of rewriting rather than negotiating is browser support, and it is
 * no longer a real cost: WebP is supported by every browser released since
 * 2020, including Safari 14. The site's own analytics would be the way to
 * check that, and there are none by design — so this is a judgement call
 * stated openly rather than a measured one.
 *
 * A reference is only rewritten when the .webp file actually exists AND is
 * smaller than the original. Both conditions matter: the first prevents 404s,
 * the second prevents the case where WebP encodes a flat graphic worse than
 * PNG does and the "optimisation" makes the page heavier.
 */

const fs = require('fs');
const path = require('path');

const DIST = path.join(__dirname, '../dist');

/** Resolve a URL as it appears in markup to a file inside dist/. */
function resolveAsset(url, fromFile) {
  const clean = url.split('?')[0].split('#')[0];
  if (/^(https?:)?\/\//i.test(clean) || clean.startsWith('data:')) return null;
  const abs = clean.startsWith('/')
    ? path.join(DIST, clean.replace(/^\//, ''))
    : path.resolve(path.dirname(fromFile), clean);
  // Never escape dist/ — a "../../../etc" in scraped markup should not make
  // this step read outside the build output.
  if (!abs.startsWith(DIST)) return null;
  return abs;
}

/**
 * Returns the WebP replacement for `url`, or null to leave it alone.
 * Memoised: the same handful of images are referenced across 230 pages.
 */
const decisions = new Map();
function webpFor(url, fromFile) {
  if (!/\.(png|jpe?g)(\?|#|$)/i.test(url)) return null;

  const key = url.split('?')[0];
  if (decisions.has(key)) {
    const cached = decisions.get(key);
    return cached === null ? null : url.replace(/\.(png|jpe?g)(?=\?|#|$)/i, '.webp');
  }

  const src = resolveAsset(url, fromFile);
  if (!src || !fs.existsSync(src)) {
    decisions.set(key, null);
    return null;
  }
  const webp = src.replace(/\.(png|jpe?g)$/i, '.webp');
  if (!fs.existsSync(webp)) {
    decisions.set(key, null);
    return null;
  }
  // Bigger as WebP means WebP lost — usually a flat graphic or a tiny icon.
  if (fs.statSync(webp).size >= fs.statSync(src).size) {
    decisions.set(key, null);
    return null;
  }

  decisions.set(key, webp);
  return url.replace(/\.(png|jpe?g)(?=\?|#|$)/i, '.webp');
}

function rewrite(text, file, stats) {
  let out = text;

  // CSS url(...) — quoted or bare.
  out = out.replace(/url\(\s*(['"]?)([^'")]+)\1\s*\)/gi, (whole, q, url) => {
    const next = webpFor(url.trim(), file);
    if (!next) return whole;
    stats.css++;
    return `url(${q}${next}${q})`;
  });

  // <img src>, and srcset candidate lists.
  out = out.replace(/<img\b[^>]*>/gi, (tag) => {
    let changed = false;
    let next = tag.replace(/\bsrc=(["'])(.*?)\1/i, (m, qq, url) => {
      const w = webpFor(url, file);
      if (!w) return m;
      changed = true;
      return `src=${qq}${w}${qq}`;
    });
    next = next.replace(/\bsrcset=(["'])(.*?)\1/i, (m, qq, list) => {
      const parts = list.split(',').map((c) => {
        const [u, ...rest] = c.trim().split(/\s+/);
        const w = webpFor(u, file);
        return w ? [w, ...rest].join(' ') : c.trim();
      });
      const joined = parts.join(', ');
      if (joined === list) return m;
      changed = true;
      return `srcset=${qq}${joined}${qq}`;
    });
    if (changed) stats.img++;
    return next;
  });

  return out;
}

function findFiles(dir, exts, results = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) findFiles(full, exts, results);
    else if (exts.some((e) => entry.name.toLowerCase().includes(e))) results.push(full);
  }
  return results;
}

function main() {
  console.log('\n🖼️  Pointing image references at the WebP versions...\n');

  const stats = { css: 0, img: 0 };
  let files = 0;
  let saved = 0;

  // .css matched loosely because the scrape keeps its query string in the
  // filename ("post-5668.css?ver=178....css").
  for (const file of findFiles(DIST, ['.html', '.css'])) {
    const text = fs.readFileSync(file, 'utf-8');
    const out = rewrite(text, file, stats);
    if (out !== text) {
      fs.writeFileSync(file, out);
      files++;
    }
  }

  for (const [orig, webp] of decisions) {
    if (!webp) continue;
    const src = path.join(DIST, orig.replace(/^\//, ''));
    if (fs.existsSync(src) && fs.existsSync(webp)) {
      saved += fs.statSync(src).size - fs.statSync(webp).size;
    }
  }

  const swapped = [...decisions.values()].filter(Boolean).length;
  const kept = [...decisions.values()].filter((v) => v === null).length;

  console.log(`✅ ${stats.css} CSS background(s) and ${stats.img} <img> tag(s) across ${files} file(s)`);
  console.log(`   • ${swapped} distinct image(s) switched to WebP`);
  console.log(`   • ${kept} left as-is (no WebP sibling, or WebP was not smaller)`);
  if (saved > 0) console.log(`   • ~${(saved / 1024).toFixed(0)}KB less per full page load of those images`);
  console.log();
}

main();
